wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    code_path: code/PredictionGame/test_agent.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1628885429
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.12.0
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 20
eps:
  desc: null
  value: 0.01
gamma:
  desc: null
  value: 0.999
lr:
  desc: null
  value: 0.005
vocab_size:
  desc: null
  value: 4
